### ISSUE TITLE
Clouds look blury although everything is left as default

### ISSUE THREAD

**Issue by yaaasir** [goat1000/TagCanvas#11]
I have been trying to solve the problem by , changing brightness, fonts, color, zoom, weight but none of them seem to work.Tried with jquery 3.4 and standalone version and everything. Blurry on every major browsers. even pasted codes from goat1000 examples.

**Comment by goat1000** [comment]
Do you have something I can look at to see what you are getting? It could be that you are using CSS to scale the canvas up without setting a high enough resolution using the canvas width and height.

**Comment by yaaasir** [comment]
Yeah I was trying to scale the canvas dynamically with JS to fit the section area. But shouldn't the draw method draw objects for that instance of canvas, I mean with the scale settings for bigger canvas? and is there any way to adjust the resolution dynamically?

**Comment by yaaasir** [comment]
Yeah, I was updating the canvas area dynamically to fit the section area. Shouldn't the objects be drawn for current instance of the canvas with current scales and all. Anyways now all I have to do is create the canvas itself dynamically with section height & width.
