### ISSUE TITLE
有在vue中使用的吗 

### ISSUE THREAD

**Issue by zg08** [goat1000/TagCanvas#13]
目前按常规方式 引入的 还需要弄dom元素 有没有vue直接使用的

**Comment by goat1000** [comment]
Google translate of this:
> 有在vue中使用的吗
> 目前按常规方式 引入的 还需要弄dom元素 有没有vue直接使用的

Gives me
> Is it used in vue
> At present, it is introduced in the usual way and needs to get the dom element. Is there any vue directly used?

I don't know anything about vue, sorry.

**Comment by zg08** [comment]
Well thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goat1000/TagCanvas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上8:08
收件人:&nbsp;"goat1000/TagCanvas"<TagCanvas@noreply.github.com&gt;;
抄送:&nbsp;"张干"<595158663@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goat1000/TagCanvas] 有在vue中使用的吗  (#13)





 
Google translate of this:
  
有在vue中使用的吗
 目前按常规方式 引入的 还需要弄dom元素 有没有vue直接使用的
  
Gives me
  
Is it used in vue
 At present, it is introduced in the usual way and needs to get the dom element. Is there any vue directly used?
  
I don't know anything about vue, sorry.

**Comment by stellarkey** [comment]
I Found this: [http://jsrun.net/aTfKp/edit](http://jsrun.net/aTfKp/edit)

**Comment by wangweizm** [comment]
我这边有在vue的案例
