### ISSUE TITLE
How to swap image when the tag is active?

### ISSUE THREAD

**Issue by Ragul184** [goat1000/TagCanvas#17]
Hi team,
You put an update for the TagCanvas that when we hover any tag in the canvas, it will swap the image with the another altImage when we set altImage: true. But it is not working for me or I didn't know whether I did it in a right way or not.

![image](https://user-images.githubusercontent.com/52290943/136131059-11505d33-3b09-4648-a2f2-d2ef86c3ba32.png)

How to do this?

**Comment by goat1000** [comment]
Enable the `altImage` option and add a second image in the tag element:
```html
<a href="page.html"> <!-- a tag element -->
   <img src="image1.png"> <!-- main image -->
   <img src="image2.png"> <!-- alt image -->
</a>
```

**Comment by Ragul184** [comment]
Yeah thanks team. I tried it and it is perfectly working. I have another doubt to ask how to achieve this kind of animation using TagCanvas?

![julian-sanmartino-google-chrome-2021-10-07-07-33-15-trim_m3LVyEs5_5Qzq](https://user-images.githubusercontent.com/52290943/136309249-1356b9f5-8c07-42a4-9afc-64a920c89b1b.gif)

How to do this type animation using this TagCanvas team? If there is a way, kindly let me know about this design! 

And this design is inspired from [Julián Sanmartino](https://juliansanmartino.netlify.app/#about)'s Website!

**Comment by wangweizm** [comment]
> 是的，谢谢团队。我尝试了一下，效果很好。我还有一个疑问想问如何使用TagCanvas实现这种动画？
> 
> ![朱利安-圣马蒂诺-google-chrome-2021-10-07-07-33-15-trim_m3LVyEs5_5Qzq](https://user-images.githubusercontent.com/52290943/136309249-1356b9f5-8c07-42a4-9afc-64a920c89b1b.gif) [ ![朱利安-圣马蒂诺-google-chrome-2021-10-07-07-33-15-trim_m3LVyEs5_5Qzq](https://user-images.githubusercontent.com/52290943/136309249-1356b9f5-8c07-42a4-9afc-64a920c89b1b.gif) ](https://user-images.githubusercontent.com/52290943/136309249-1356b9f5-8c07-42a4-9afc-64a920c89b1b.gif) [ ](https://user-images.githubusercontent.com/52290943/136309249-1356b9f5-8c07-42a4-9afc-64a920c89b1b.gif)
> 
> 如何使用 TagCanvas 团队制作这种类型的动画？如果有办法，请告诉我这个设计！
> 
> 而这个设计的灵感来自于[Julián Sanmartino](https://juliansanmartino.netlify.app/#about)的网站！

May I ask how to achieve this?

**Comment by goat1000** [comment]
The linked website is not using TagCanvas, it appears to be moving HTML elements around.
