### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jmvelasco** [goat1000/TagCanvas#18]
Hello, I am looking for TS support. Trying to adding by myself but I don't have expertise enough on this matter.
Could you please help me to do it or provide?

Looking forward some comments.
Thanks!

**Comment by goat1000** [comment]
I have never looked at Typescript, so I don't think I can help you, sorry.

**Comment by jmvelasco** [comment]
Thanks for your reply. I finally added a module with just the name of the library and at least the linter doesn't complain.
If I get to define a proper @types/TagCanvas I will share it.
Have a good time.
